### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PointMicro** [MicroTrail23/GFaq-Title-Block#2]
- [ ] Add background to UI
- [ ] Add UI functions
- [ ] When user presses Add, they should be able to delete the added filter
- [ ] Remembers the filters
